apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host:
    https:
      paths:
      - path: /
        pathType: Prefix
        backend:  
        service:
          name:
            clawmanager-frontend
          port:
            number: 443
