apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 type: NodePort         // 有配置NodePort，外部流量可访问k8s中的服务
 ports:
 - port: 30080          // 服务访问端口，集群内部访问的端口
   targetPort: 30443       // pod控制器中定义的端口（应用访问的端口）
   nodePort: 443     // NodePort，外部客户端访问的端口
 selector:
  name: nginx-pod
